# Generated by Django 5.1.3 on 2024-11-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_image_filter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_filter",
            field=models.CharField(
                choices=[
                    ("_1977", "1977"),
                    ("brannan", "Brannan"),
                    ("earlybird", "Earlybird"),
                    ("hudson", "Hudson"),
                    ("inkwell", "Inkwell"),
                    ("lofi", "Lo-Fi"),
                    ("kelvin", "Kelvin"),
                    ("normal", "Normal"),
                    ("nashville", "Nashville"),
                    ("rise", "Rise"),
                    ("toaster", "Toaster"),
                    ("valencia", "Valencia"),
                    ("walden", "Walden"),
                    ("xpro2", "X-pro II"),
                ],
                default="normal",
                max_length=32,
            ),
        ),
    ]
