# Generated by Django 5.1.3 on 2024-11-28 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="../default_post_rgq6aq",
                        upload_to="images/",
                    ),
                ),
                (
                    "image_filter",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("clarendon", "Clarendon"),
                            ("gingham", "Gingham"),
                            ("moon", "Moon"),
                            ("lark", "Lark"),
                            ("reyes", "Reyes"),
                            ("juno", "Juno"),
                            ("slumber", "Slumber"),
                            ("aden", "Aden"),
                            ("perpetua", "Perpetua"),
                            ("mayfair", "Mayfair"),
                            ("rise", "Rise"),
                            ("hudson", "Hudson"),
                            ("valencia", "Valencia"),
                            ("xpro2", "X-Pro II"),
                            ("willow", "Willow"),
                            ("lofi", "Lo-Fi"),
                            ("inkwell", "Inkwell"),
                            ("nashville", "Nashville"),
                            ("amaro", "Amaro"),
                            ("brannan", "Brannan"),
                            ("earlybird", "Earlybird"),
                            ("sutro", "Sutro"),
                            ("toaster", "Toaster"),
                            ("walden", "Walden"),
                            ("1977", "1977"),
                            ("kelvin", "Kelvin"),
                        ],
                        default="normal",
                        max_length=32,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
