# Generated by Django 5.1.3 on 2024-11-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_filter",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("clarendon", "Clarendon"),
                    ("gingham", "Gingham"),
                    ("moon", "Moon"),
                    ("lark", "Lark"),
                    ("reyes", "Reyes"),
                    ("juno", "Juno"),
                    ("slumber", "Slumber"),
                    ("aden", "Aden"),
                    ("perpetua", "Perpetua"),
                    ("mayfair", "Mayfair"),
                    ("rise", "Rise"),
                    ("hudson", "Hudson"),
                    ("valencia", "Valencia"),
                    ("xpro2", "X-Pro II"),
                    ("willow", "Willow"),
                    ("lofi", "Lo-Fi"),
                    ("inkwell", "Inkwell"),
                    ("nashville", "Nashville"),
                    ("amaro", "Amaro"),
                    ("brannan", "Brannan"),
                    ("earlybird", "Earlybird"),
                    ("sutro", "Sutro"),
                    ("toaster", "Toaster"),
                    ("walden", "Walden"),
                    ("1977", "1977"),
                    ("kelvin", "Kelvin"),
                ],
                default="normal",
                max_length=32,
            ),
        ),
    ]
